### ISSUE TITLE
pytorch3d 的安装 pip install -e .命令一直有问题

### ISSUE THREAD

**Issue by 2601705041** [hzhao1997/HF-Avatar#39]
Obtaining file:///home/j222/HF-Avatar-main/pytorch3d-0.4.0
Requirement already satisfied: fvcore in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from pytorch3d==0.4.0)
Requirement already satisfied: iopath in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from pytorch3d==0.4.0)
Requirement already satisfied: pyyaml>=5.1 in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: Pillow in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: tabulate in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: termcolor>=1.1 in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: numpy in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: tqdm in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: dataclasses; python_version < "3.7" in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: yacs>=0.1.6 in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from fvcore->pytorch3d==0.4.0)
Requirement already satisfied: typing-extensions in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from iopath->pytorch3d==0.4.0)
Requirement already satisfied: portalocker in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from iopath->pytorch3d==0.4.0)
Requirement already satisfied: importlib-resources; python_version < "3.7" in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from tqdm->fvcore->pytorch3d==0.4.0)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /home/j222/anaconda/envs/ava/lib/python3.6/site-packages (from importlib-resources; python_version < "3.7"->tqdm->fvcore->pytorch3d==0.4.0)
Installing collected packages: pytorch3d
  Running setup.py develop for pytorch3d
    Complete output from command /home/j222/anaconda/envs/ava/bin/python -c "import setuptools, tokenize;__file__='/home/j222/HF-Avatar-main/pytorch3d-0.4.0/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing pytorch3d.egg-info/PKG-INFO
    writing dependency_links to pytorch3d.egg-info/dependency_links.txt
    writing requirements to pytorch3d.egg-info/requires.txt
    writing top-level names to pytorch3d.egg-info/top_level.txt
    reading manifest file 'pytorch3d.egg-info/SOURCES.txt'
    writing manifest file 'pytorch3d.egg-info/SOURCES.txt'
    running build_ext
    building 'pytorch3d._C' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/j222/HF-Avatar-main/pytorch3d-0.4.0/setup.py", line 144, in <module>
        cmdclass={"build_ext": BuildExtension},
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/setuptools/command/develop.py", line 134, in install_for_development
        self.run_command('build_ext')
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
        build_ext.build_extensions(self)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 468, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 377, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags) +
      File "/home/j222/anaconda/envs/ava/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1421, in _get_cuda_arch_flags
        raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
    ValueError: Unknown CUDA arch (8.9) or GPU not supported
    
    ----------------------------------------
Command "/home/j222/anaconda/envs/ava/bin/python -c "import setuptools, tokenize;__file__='/home/j222/HF-Avatar-main/pytorch3d-0.4.0/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/j222/HF-Avatar-main/pytorch3d-0.4.0/
You are using pip version 9.0.1, however version 23.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

我的环境：pytorch==1.7.0 torchvision==0.8.0 cudatoolkit=11.0    gcc 9.4.0
pytorch3d0.5.0 \ 0.7.0 \0.7.1 等安装都有问题

**Comment by alpttex19** [comment]
可以尝试一下使用别的方法安装pytorch3d

**Comment by hzhao1997** [comment]
根据这两行 raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.9) or GPU not supported
你的机器有显卡吗 并且正确安装cuda了吗
