### ISSUE TITLE
Is there any way to install it with the latest pytorch, pytorch3D on Win 11 + VS2019

### ISSUE THREAD

**Issue by xqyd** [hzhao1997/HF-Avatar#5]
Thanks for the great job!

 It appears to me that your guide of installation is for the old version of pytorch, pytorch3d, and neural_renderer. In my case,  I had to run everything on Win11 + VS2019.  I can figure out the installation of pytorch3d (latest) with cuda 11.x. But I was facing difficulty of installing the old neural_renderer. I've tried the recipe from https://github.com/lstcutong/neural_renderer_pytorch-win10, but get no luck.  I guess it cannot work with cuda > 11.0 ?

If I follow your intallation guidelines, the neural_renderer can be compiled without any problem, but the pytorch3d 0.4.0 will pop up tons of errors that related with c++14, nvcc, ninja, etc., just like the one reported at https://github.com/iPERDance/iPERCore/issues/12.

Anyway, is there a way to install the neural_renderer with the latest pytorch, pytorch3d? Please help me out!

**Comment by xqyd** [comment]
Thanks for the heads up. I have a lot of other codes depend on cuda 11.x so I kind of have to use newer env for your code. Anyway, after searching around, I've found a solution to modify the neural_render for compiling successful with latest pytorch (1.12.1 + cuda 11.3) and latest pytorch3d (0.7.0). (https://zhuanlan.zhihu.com/p/454832455  )

However, I'm still facing problem when running dynamic_offsets_runner.py. The output follows.

==========
C:\Users\000\anaconda3\envs\avatar2\python.exe D:/HF-Avatar-main/dynamic_offsets_runner.py
deal with Body2D_2040_499
496
pose_lr: 0.0005 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 0: body_joints_loss 0.0012308069271966815 face_joints_loss 0.000253313803113997 a_pose_prior_loss 0.1399410367012024 temporal_loss 6.803683936595917e-05
pose_lr: 0.00048666666666666666 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 20: body_joints_loss 0.0007467379909940064 face_joints_loss 3.77301184926182e-05 a_pose_prior_loss 0.13823160529136658 temporal_loss 2.145877806469798e-05
pose_lr: 0.00047333333333333336 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 40: body_joints_loss 0.0005183664616197348 face_joints_loss 2.0153687728452496e-05 a_pose_prior_loss 0.13675881922245026 temporal_loss 1.1691283361869864e-05
pose_lr: 0.00046 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 60: body_joints_loss 0.0004000658227596432 face_joints_loss 1.825666186050512e-05 a_pose_prior_loss 0.13528133928775787 temporal_loss 7.7563081504195e-06
pose_lr: 0.00044666666666666666 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 80: body_joints_loss 0.0003288703446742147 face_joints_loss 1.7135611415142193e-05 a_pose_prior_loss 0.13368374109268188 temporal_loss 5.8272316891816445e-06
pose_lr: 0.0004333333333333333 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 100: body_joints_loss 0.0002824698749464005 face_joints_loss 1.6413721823482774e-05 a_pose_prior_loss 0.1320117712020874 temporal_loss 4.643287866201717e-06
pose_lr: 0.00042 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 120: body_joints_loss 0.00025019669556058943 face_joints_loss 1.5870618881308474e-05 a_pose_prior_loss 0.13035769760608673 temporal_loss 3.852675035886932e-06
pose_lr: 0.00040666666666666667 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 140: body_joints_loss 0.0002265885705128312 face_joints_loss 1.5448920748895034e-05 a_pose_prior_loss 0.1287619024515152 temporal_loss 3.302234972579754e-06
pose_lr: 0.0003933333333333333 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 160: body_joints_loss 0.00020858774951193482 face_joints_loss 1.5115073438209947e-05 a_pose_prior_loss 0.12723977863788605 temporal_loss 2.9017382985330187e-06
pose_lr: 0.00038 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 180: body_joints_loss 0.00019436916045378894 face_joints_loss 1.4846345948171802e-05 a_pose_prior_loss 0.1257980763912201 temporal_loss 2.601080495878705e-06
pose_lr: 0.00036666666666666667 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 200: body_joints_loss 0.00018279688083566725 face_joints_loss 1.4627429663960356e-05 a_pose_prior_loss 0.12443770468235016 temporal_loss 2.3696459265920566e-06
pose_lr: 0.0003533333333333333 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 220: body_joints_loss 0.00017314343131147325 face_joints_loss 1.4447070498135872e-05 a_pose_prior_loss 0.12315767258405685 temporal_loss 2.187597146985354e-06
pose_lr: 0.00034 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 240: body_joints_loss 0.00016492829308845103 face_joints_loss 1.4296879271569196e-05 a_pose_prior_loss 0.12195603549480438 temporal_loss 2.041735569946468e-06
pose_lr: 0.0003266666666666667 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 260: body_joints_loss 0.000157824601046741 face_joints_loss 1.417050134477904e-05 a_pose_prior_loss 0.12083037197589874 temporal_loss 1.9229919416829944e-06
pose_lr: 0.0003133333333333333 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 280: body_joints_loss 0.0001516036718385294 face_joints_loss 1.4063104572414886e-05 a_pose_prior_loss 0.11977805942296982 temporal_loss 1.8250307221023832e-06
pose_lr: 0.00030000000000000003 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 300: body_joints_loss 0.0001461013889638707 face_joints_loss 1.397097366861999e-05 a_pose_prior_loss 0.11879623681306839 temporal_loss 1.7432836330044665e-06
pose_lr: 0.0002866666666666667 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 320: body_joints_loss 0.00014119618572294712 face_joints_loss 1.3891319213144016e-05 a_pose_prior_loss 0.11788195371627808 temporal_loss 1.674360873948899e-06
pose_lr: 0.00027333333333333333 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 340: body_joints_loss 0.00013679714174941182 face_joints_loss 1.3821836546412669e-05 a_pose_prior_loss 0.11703215539455414 temporal_loss 1.6157628124346957e-06
pose_lr: 0.00026000000000000003 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 360: body_joints_loss 0.00013283314183354378 face_joints_loss 1.3760813999397215e-05 a_pose_prior_loss 0.11624372005462646 temporal_loss 1.5656100913474802e-06
pose_lr: 0.0002466666666666667 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 380: body_joints_loss 0.00012924824841320515 face_joints_loss 1.370685549773043e-05 a_pose_prior_loss 0.11551357060670853 temporal_loss 1.5224078424580512e-06
pose_lr: 0.00023333333333333333 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 400: body_joints_loss 0.00012599707406479865 face_joints_loss 1.3658857824339066e-05 a_pose_prior_loss 0.1148386225104332 temporal_loss 1.4849978242637007e-06
pose_lr: 0.00021999999999999998 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 420: body_joints_loss 0.00012304254050832242 face_joints_loss 1.3615909665531944e-05 a_pose_prior_loss 0.11421594768762589 temporal_loss 1.4523940308208694e-06
pose_lr: 0.00020666666666666668 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 440: body_joints_loss 0.0001203529755002819 face_joints_loss 1.357728979201056e-05 a_pose_prior_loss 0.11364272236824036 temporal_loss 1.4240174550650408e-06
pose_lr: 0.00019333333333333333 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 460: body_joints_loss 0.00011790287680923939 face_joints_loss 1.3542321539716795e-05 a_pose_prior_loss 0.1131162941455841 temporal_loss 1.3991066225571558e-06
pose_lr: 0.00017999999999999998 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 480: body_joints_loss 0.00011566960165509954 face_joints_loss 1.351050832454348e-05 a_pose_prior_loss 0.11263421177864075 temporal_loss 1.3772545344181708e-06
pose_lr: 0.00016666666666666663 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 500: body_joints_loss 0.00011363394150976092 face_joints_loss 1.3481453606800642e-05 a_pose_prior_loss 0.1121942549943924 temporal_loss 1.3580445283878362e-06
pose_lr: 0.00015333333333333334 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 520: body_joints_loss 0.00011177945998497307 face_joints_loss 1.345477176073473e-05 a_pose_prior_loss 0.1117943525314331 temporal_loss 1.3411510053629172e-06
pose_lr: 0.00014 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 540: body_joints_loss 0.00011009222362190485 face_joints_loss 1.3430152648652438e-05 a_pose_prior_loss 0.11143271625041962 temporal_loss 1.3263183973322157e-06
pose_lr: 0.00012666666666666664 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 560: body_joints_loss 0.00010855973232537508 face_joints_loss 1.3407360711426008e-05 a_pose_prior_loss 0.1111077293753624 temporal_loss 1.3132826097717043e-06
pose_lr: 0.00011333333333333334 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 580: body_joints_loss 0.00010717236727941781 face_joints_loss 1.3386098544287961e-05 a_pose_prior_loss 0.11081802099943161 temporal_loss 1.3019565585636883e-06
pose_lr: 9.999999999999999e-05 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 600: body_joints_loss 0.00010592067701509222 face_joints_loss 1.3366285202209838e-05 a_pose_prior_loss 0.11056239157915115 temporal_loss 1.2920801282234606e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 620: body_joints_loss 0.00010475726594449952 face_joints_loss 1.3347233107197098e-05 a_pose_prior_loss 0.11032479256391525 temporal_loss 1.28311148728244e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 640: body_joints_loss 0.00010363145702285692 face_joints_loss 1.3328671229828615e-05 a_pose_prior_loss 0.11008751392364502 temporal_loss 1.2743502111334237e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 660: body_joints_loss 0.00010254091466777027 face_joints_loss 1.3310573194758035e-05 a_pose_prior_loss 0.10984986275434494 temporal_loss 1.265866785615799e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 680: body_joints_loss 0.00010148392902920023 face_joints_loss 1.3292914445628412e-05 a_pose_prior_loss 0.10961173474788666 temporal_loss 1.2576028893818147e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 700: body_joints_loss 0.00010045933595392853 face_joints_loss 1.3275616765895393e-05 a_pose_prior_loss 0.10937319695949554 temporal_loss 1.2495664805101114e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 720: body_joints_loss 9.946515638148412e-05 face_joints_loss 1.3258785656944383e-05 a_pose_prior_loss 0.10913429409265518 temporal_loss 1.2417086736604688e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 740: body_joints_loss 9.850115020526573e-05 face_joints_loss 1.3242164641269483e-05 a_pose_prior_loss 0.10889510810375214 temporal_loss 1.233995476468408e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 760: body_joints_loss 9.756530926097184e-05 face_joints_loss 1.3225880138634238e-05 a_pose_prior_loss 0.10865574330091476 temporal_loss 1.22650169487315e-06
pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001
epoch_idx 780: body_joints_loss 9.665657125879079e-05 face_joints_loss 1.3209883036324754e-05 a_pose_prior_loss 0.10841624438762665 temporal_loss 1.2192133453936549e-06
100%|██████████| 496/496 [11:06<00:00,  1.34s/it]
--------------- Epoch: 0 ---------------
C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\torch\nn\functional.py:4215: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\transforms\transform3d.py:802: UserWarning: R is not a valid rotation matrix
  warnings.warn(msg)
Traceback (most recent call last):
  File "D:/HF-Avatar-main/dynamic_offsets_runner.py", line 345, in <module>
    trainer.train()
  File "D:/HF-Avatar-main/dynamic_offsets_runner.py", line 177, in train
    loss = self.forward(step, item, input, ground_truth)
  File "D:/HF-Avatar-main/dynamic_offsets_runner.py", line 144, in forward
    model_output = self.network.forward(item, input['naked_vertice_uv'])
  File "D:\HF-Avatar-main\geometry_model\network.py", line 815, in forward
    images = self.renderer(mesh)
  File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\renderer.py", line 62, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\shader.py", line 126, in forward
    texels = meshes.sample_textures(fragments)
  File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\structures\meshes.py", line 1552, in sample_textures
    return self.textures.sample_textures(
  File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\textures.py", line 958, in sample_textures
    packing_list = [
  File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\textures.py", line 959, in <listcomp>
    i[j] for i, j in zip(self.verts_uvs_list(), self.faces_uvs_list())
IndexError: tensors used as indices must be long, byte or bool tensors

Process finished with exit code 1
========
Any idea how to solve it? Thanks!

**Comment by hzhao1997** [comment]
Hard to see, it seems that the face index is not loaded correctly. Please check this line:https://github.com/hzhao1997/HF-Avatar/blob/d656820ef1224132ab0b417eb74018be8c797e60/geometry_model/network.py#L688 the value of `f`.

**Comment by rulke** [comment]
> 

I encountered the same problem, how did you solve it? thanks

**Comment by rulke** [comment]
> Thanks for the heads up. I have a lot of other codes depend on cuda 11.x so I kind of have to use newer env for your code. Anyway, after searching around, I've found a solution to modify the neural_render for compiling successful with latest pytorch (1.12.1 + cuda 11.3) and latest pytorch3d (0.7.0). (https://zhuanlan.zhihu.com/p/454832455 )
> 
> However, I'm still facing problem when running dynamic_offsets_runner.py. The output follows.
> 
> ========== C:\Users\000\anaconda3\envs\avatar2\python.exe D:/HF-Avatar-main/dynamic_offsets_runner.py deal with Body2D_2040_499 496 pose_lr: 0.0005 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 0: body_joints_loss 0.0012308069271966815 face_joints_loss 0.000253313803113997 a_pose_prior_loss 0.1399410367012024 temporal_loss 6.803683936595917e-05 pose_lr: 0.00048666666666666666 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 20: body_joints_loss 0.0007467379909940064 face_joints_loss 3.77301184926182e-05 a_pose_prior_loss 0.13823160529136658 temporal_loss 2.145877806469798e-05 pose_lr: 0.00047333333333333336 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 40: body_joints_loss 0.0005183664616197348 face_joints_loss 2.0153687728452496e-05 a_pose_prior_loss 0.13675881922245026 temporal_loss 1.1691283361869864e-05 pose_lr: 0.00046 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 60: body_joints_loss 0.0004000658227596432 face_joints_loss 1.825666186050512e-05 a_pose_prior_loss 0.13528133928775787 temporal_loss 7.7563081504195e-06 pose_lr: 0.00044666666666666666 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 80: body_joints_loss 0.0003288703446742147 face_joints_loss 1.7135611415142193e-05 a_pose_prior_loss 0.13368374109268188 temporal_loss 5.8272316891816445e-06 pose_lr: 0.0004333333333333333 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 100: body_joints_loss 0.0002824698749464005 face_joints_loss 1.6413721823482774e-05 a_pose_prior_loss 0.1320117712020874 temporal_loss 4.643287866201717e-06 pose_lr: 0.00042 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 120: body_joints_loss 0.00025019669556058943 face_joints_loss 1.5870618881308474e-05 a_pose_prior_loss 0.13035769760608673 temporal_loss 3.852675035886932e-06 pose_lr: 0.00040666666666666667 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 140: body_joints_loss 0.0002265885705128312 face_joints_loss 1.5448920748895034e-05 a_pose_prior_loss 0.1287619024515152 temporal_loss 3.302234972579754e-06 pose_lr: 0.0003933333333333333 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 160: body_joints_loss 0.00020858774951193482 face_joints_loss 1.5115073438209947e-05 a_pose_prior_loss 0.12723977863788605 temporal_loss 2.9017382985330187e-06 pose_lr: 0.00038 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 180: body_joints_loss 0.00019436916045378894 face_joints_loss 1.4846345948171802e-05 a_pose_prior_loss 0.1257980763912201 temporal_loss 2.601080495878705e-06 pose_lr: 0.00036666666666666667 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 200: body_joints_loss 0.00018279688083566725 face_joints_loss 1.4627429663960356e-05 a_pose_prior_loss 0.12443770468235016 temporal_loss 2.3696459265920566e-06 pose_lr: 0.0003533333333333333 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 220: body_joints_loss 0.00017314343131147325 face_joints_loss 1.4447070498135872e-05 a_pose_prior_loss 0.12315767258405685 temporal_loss 2.187597146985354e-06 pose_lr: 0.00034 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 240: body_joints_loss 0.00016492829308845103 face_joints_loss 1.4296879271569196e-05 a_pose_prior_loss 0.12195603549480438 temporal_loss 2.041735569946468e-06 pose_lr: 0.0003266666666666667 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 260: body_joints_loss 0.000157824601046741 face_joints_loss 1.417050134477904e-05 a_pose_prior_loss 0.12083037197589874 temporal_loss 1.9229919416829944e-06 pose_lr: 0.0003133333333333333 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 280: body_joints_loss 0.0001516036718385294 face_joints_loss 1.4063104572414886e-05 a_pose_prior_loss 0.11977805942296982 temporal_loss 1.8250307221023832e-06 pose_lr: 0.00030000000000000003 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 300: body_joints_loss 0.0001461013889638707 face_joints_loss 1.397097366861999e-05 a_pose_prior_loss 0.11879623681306839 temporal_loss 1.7432836330044665e-06 pose_lr: 0.0002866666666666667 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 320: body_joints_loss 0.00014119618572294712 face_joints_loss 1.3891319213144016e-05 a_pose_prior_loss 0.11788195371627808 temporal_loss 1.674360873948899e-06 pose_lr: 0.00027333333333333333 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 340: body_joints_loss 0.00013679714174941182 face_joints_loss 1.3821836546412669e-05 a_pose_prior_loss 0.11703215539455414 temporal_loss 1.6157628124346957e-06 pose_lr: 0.00026000000000000003 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 360: body_joints_loss 0.00013283314183354378 face_joints_loss 1.3760813999397215e-05 a_pose_prior_loss 0.11624372005462646 temporal_loss 1.5656100913474802e-06 pose_lr: 0.0002466666666666667 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 380: body_joints_loss 0.00012924824841320515 face_joints_loss 1.370685549773043e-05 a_pose_prior_loss 0.11551357060670853 temporal_loss 1.5224078424580512e-06 pose_lr: 0.00023333333333333333 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 400: body_joints_loss 0.00012599707406479865 face_joints_loss 1.3658857824339066e-05 a_pose_prior_loss 0.1148386225104332 temporal_loss 1.4849978242637007e-06 pose_lr: 0.00021999999999999998 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 420: body_joints_loss 0.00012304254050832242 face_joints_loss 1.3615909665531944e-05 a_pose_prior_loss 0.11421594768762589 temporal_loss 1.4523940308208694e-06 pose_lr: 0.00020666666666666668 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 440: body_joints_loss 0.0001203529755002819 face_joints_loss 1.357728979201056e-05 a_pose_prior_loss 0.11364272236824036 temporal_loss 1.4240174550650408e-06 pose_lr: 0.00019333333333333333 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 460: body_joints_loss 0.00011790287680923939 face_joints_loss 1.3542321539716795e-05 a_pose_prior_loss 0.1131162941455841 temporal_loss 1.3991066225571558e-06 pose_lr: 0.00017999999999999998 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 480: body_joints_loss 0.00011566960165509954 face_joints_loss 1.351050832454348e-05 a_pose_prior_loss 0.11263421177864075 temporal_loss 1.3772545344181708e-06 pose_lr: 0.00016666666666666663 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 500: body_joints_loss 0.00011363394150976092 face_joints_loss 1.3481453606800642e-05 a_pose_prior_loss 0.1121942549943924 temporal_loss 1.3580445283878362e-06 pose_lr: 0.00015333333333333334 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 520: body_joints_loss 0.00011177945998497307 face_joints_loss 1.345477176073473e-05 a_pose_prior_loss 0.1117943525314331 temporal_loss 1.3411510053629172e-06 pose_lr: 0.00014 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 540: body_joints_loss 0.00011009222362190485 face_joints_loss 1.3430152648652438e-05 a_pose_prior_loss 0.11143271625041962 temporal_loss 1.3263183973322157e-06 pose_lr: 0.00012666666666666664 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 560: body_joints_loss 0.00010855973232537508 face_joints_loss 1.3407360711426008e-05 a_pose_prior_loss 0.1111077293753624 temporal_loss 1.3132826097717043e-06 pose_lr: 0.00011333333333333334 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 580: body_joints_loss 0.00010717236727941781 face_joints_loss 1.3386098544287961e-05 a_pose_prior_loss 0.11081802099943161 temporal_loss 1.3019565585636883e-06 pose_lr: 9.999999999999999e-05 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 600: body_joints_loss 0.00010592067701509222 face_joints_loss 1.3366285202209838e-05 a_pose_prior_loss 0.11056239157915115 temporal_loss 1.2920801282234606e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 620: body_joints_loss 0.00010475726594449952 face_joints_loss 1.3347233107197098e-05 a_pose_prior_loss 0.11032479256391525 temporal_loss 1.28311148728244e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 640: body_joints_loss 0.00010363145702285692 face_joints_loss 1.3328671229828615e-05 a_pose_prior_loss 0.11008751392364502 temporal_loss 1.2743502111334237e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 660: body_joints_loss 0.00010254091466777027 face_joints_loss 1.3310573194758035e-05 a_pose_prior_loss 0.10984986275434494 temporal_loss 1.265866785615799e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 680: body_joints_loss 0.00010148392902920023 face_joints_loss 1.3292914445628412e-05 a_pose_prior_loss 0.10961173474788666 temporal_loss 1.2576028893818147e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 700: body_joints_loss 0.00010045933595392853 face_joints_loss 1.3275616765895393e-05 a_pose_prior_loss 0.10937319695949554 temporal_loss 1.2495664805101114e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 720: body_joints_loss 9.946515638148412e-05 face_joints_loss 1.3258785656944383e-05 a_pose_prior_loss 0.10913429409265518 temporal_loss 1.2417086736604688e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 740: body_joints_loss 9.850115020526573e-05 face_joints_loss 1.3242164641269483e-05 a_pose_prior_loss 0.10889510810375214 temporal_loss 1.233995476468408e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 760: body_joints_loss 9.756530926097184e-05 face_joints_loss 1.3225880138634238e-05 a_pose_prior_loss 0.10865574330091476 temporal_loss 1.22650169487315e-06 pose_lr: 0.0001 betas_lr: 0.001 trans_lr: 0.001 epoch_idx 780: body_joints_loss 9.665657125879079e-05 face_joints_loss 1.3209883036324754e-05 a_pose_prior_loss 0.10841624438762665 temporal_loss 1.2192133453936549e-06 100%|██████████| 496/496 [11:06<00:00, 1.34s/it] --------------- Epoch: 0 --------------- C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\torch\nn\functional.py:4215: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details. warnings.warn( C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\transforms\transform3d.py:802: UserWarning: R is not a valid rotation matrix warnings.warn(msg) Traceback (most recent call last): File "D:/HF-Avatar-main/dynamic_offsets_runner.py", line 345, in trainer.train() File "D:/HF-Avatar-main/dynamic_offsets_runner.py", line 177, in train loss = self.forward(step, item, input, ground_truth) File "D:/HF-Avatar-main/dynamic_offsets_runner.py", line 144, in forward model_output = self.network.forward(item, input['naked_vertice_uv']) File "D:\HF-Avatar-main\geometry_model\network.py", line 815, in forward images = self.renderer(mesh) File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\renderer.py", line 62, in forward images = self.shader(fragments, meshes_world, **kwargs) File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\shader.py", line 126, in forward texels = meshes.sample_textures(fragments) File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\structures\meshes.py", line 1552, in sample_textures return self.textures.sample_textures( File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\textures.py", line 958, in sample_textures packing_list = [ File "C:\Users\000\anaconda3\envs\avatar2\lib\site-packages\pytorch3d-0.7.0-py3.8-win-amd64.egg\pytorch3d\renderer\mesh\textures.py", line 959, in i[j] for i, j in zip(self.verts_uvs_list(), self.faces_uvs_list()) IndexError: tensors used as indices must be long, byte or bool tensors
> 
> Process finished with exit code 1
> 
> Any idea how to solve it? Thanks!

I encountered the same problem, how did you solve it? thanks

**Comment by hzhao1997** [comment]
> > Hard to see, it seems that the face index is not loaded correctly. Please check this line:
> > https://github.com/hzhao1997/HF-Avatar/blob/d656820ef1224132ab0b417eb74018be8c797e60/geometry_model/network.py#L688
> > 
> > the value of `f`.
> 
> Hello, how can I solve it?Thanks

print(f) directly.

In the meanwhile, we only test the code with pytorch3d=0.4.0. There is no guarantee that other versions, like 0.7.0, will work.

**Comment by MilesTheProwler** [comment]
Hi did you solve it ? I have many error such as pytorch3d and neural-renderer-pytorch. Can someone help me to solve it ?
